var electorates = {
  "results": {
"..": {"map_id": "", "edname": "","region": "","election_2012": "","current_party": ""}, 
"01": {"map_id": "1","edname": "Dunvegan-Central Peace-Notley","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"02": {"map_id": "2","edname": "Lesser Slave Lake","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"03": {"map_id": "3","edname": "Calgary-Acadia","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"04": {"map_id": "4","edname": "Calgary-Bow","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"05": {"map_id": "5","edname": "Calgary-Buffalo","region": "Calgary","election_2012": "PC","current_party": "LIB","totalvotes": "15000"},
"06": {"map_id": "6","edname": "Calgary-Cross","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"07": {"map_id": "7","edname": "Calgary-Currie","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"08": {"map_id": "8","edname": "Calgary-East","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"09": {"map_id": "9","edname": "Calgary-Elbow","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"10": {"map_id": "10","edname": "Calgary-Fish Creek","region": "Calgary","election_2012": "WRP","current_party": "WRP","totalvotes": "15000"},
"11": {"map_id": "11","edname": "Calgary-Foothills","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"12": {"map_id": "12","edname": "Calgary-Fort","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"13": {"map_id": "13","edname": "Calgary-Glenmore","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"14": {"map_id": "14","edname": "Calgary-Greenway","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"15": {"map_id": "15","edname": "Calgary-Hawkwood","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"16": {"map_id": "16","edname": "Calgary-Hays","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"17": {"map_id": "17","edname": "Calgary-Klein","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"18": {"map_id": "18","edname": "Calgary-Lougheed","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"19": {"map_id": "19","edname": "Calgary-Mackay-Nose Hill","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"20": {"map_id": "20","edname": "Calgary-McCall","region": "Calgary","election_2012": "LIB","current_party": "LIB","totalvotes": "15000"},
"21": {"map_id": "21","edname": "Calgary-Mountain View","region": "Calgary","election_2012": "LIB","current_party": "LIB","totalvotes": "15000"},
"22": {"map_id": "22","edname": "Calgary-North West","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"23": {"map_id": "23","edname": "Calgary-Northern Hills","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"24": {"map_id": "24","edname": "Calgary-Shaw","region": "Calgary","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"25": {"map_id": "25","edname": "Calgary-South East","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"26": {"map_id": "26","edname": "Calgary-Varsity","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"27": {"map_id": "27","edname": "Calgary-West","region": "Calgary","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"28": {"map_id": "28","edname": "Edmonton-Beverly-Clareview","region": "Edmonton","election_2012": "NDP","current_party": "NDP","totalvotes": "15000"},
"29": {"map_id": "29","edname": "Edmonton-Calder","region": "Edmonton","election_2012": "NDP","current_party": "NDP","totalvotes": "15000"},
"30": {"map_id": "30","edname": "Edmonton-Castle Downs","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"31": {"map_id": "31","edname": "Edmonton-Centre","region": "Edmonton","election_2012": "LIB","current_party": "LIB","totalvotes": "15000"},
"32": {"map_id": "32","edname": "Edmonton-Decore","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"33": {"map_id": "33","edname": "Edmonton-Ellerslie","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"34": {"map_id": "34","edname": "Edmonton-Glenora","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"35": {"map_id": "35","edname": "Edmonton-Gold Bar","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"36": {"map_id": "36","edname": "Edmonton-Highlands-Norwood","region": "Edmonton","election_2012": "NDP","current_party": "NDP","totalvotes": "15000"},
"37": {"map_id": "37","edname": "Edmonton-Manning","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"38": {"map_id": "38","edname": "Edmonton-McClung","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"39": {"map_id": "39","edname": "Edmonton-Meadowlark","region": "Edmonton","election_2012": "LIB","current_party": "LIB","totalvotes": "15000"},
"40": {"map_id": "40","edname": "Edmonton-Mill Creek","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"41": {"map_id": "41","edname": "Edmonton-Mill Woods","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"42": {"map_id": "42","edname": "Edmonton-Riverview","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"43": {"map_id": "43","edname": "Edmonton-Rutherford","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"44": {"map_id": "44","edname": "Edmonton-South West","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"45": {"map_id": "45","edname": "Edmonton-Strathcona","region": "Edmonton","election_2012": "NDP","current_party": "NDP","totalvotes": "15000"},
"46": {"map_id": "46","edname": "Edmonton-Whitemud","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"47": {"map_id": "47","edname": "Airdrie","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"48": {"map_id": "48","edname": "Athabasca-Sturgeon-Redwater","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"49": {"map_id": "49","edname": "Banff-Cochrane","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"50": {"map_id": "50","edname": "Barrhead-Morinville-Westlock","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"51": {"map_id": "51","edname": "Battle River-Wainwright","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"52": {"map_id": "52","edname": "Bonnyville-Cold Lake","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"53": {"map_id": "53","edname": "Cardston-Taber-Warner","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"54": {"map_id": "54","edname": "Chestermere-Rocky View","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"55": {"map_id": "55","edname": "Cypress-Medicine Hat","region": "Rest of Alberta","election_2012": "WRP","current_party": "WRP","totalvotes": "15000"},
"56": {"map_id": "56","edname": "Drayton Valley-Devon","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"57": {"map_id": "57","edname": "Drumheller-Stettler","region": "Rest of Alberta","election_2012": "WRP","current_party": "WRP","totalvotes": "15000"},
"58": {"map_id": "58","edname": "Fort McMurray-Conklin","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"59": {"map_id": "59","edname": "Fort McMurray-Wood Buffalo","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"60": {"map_id": "60","edname": "Fort Saskatchewan-Vegreville","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"61": {"map_id": "61","edname": "Grande Prairie-Smoky","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"62": {"map_id": "62","edname": "Grande Prairie-Wapiti","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"63": {"map_id": "63","edname": "Highwood","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"64": {"map_id": "64","edname": "Innisfail-Sylvan Lake","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"65": {"map_id": "65","edname": "Lac La Biche-St. Paul-Two Hills","region": "Rest of Alberta","election_2012": "WRP","current_party": "WRP","totalvotes": "15000"},
"66": {"map_id": "66","edname": "Lacombe-Ponoka","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"67": {"map_id": "67","edname": "Leduc-Beaumont","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"68": {"map_id": "68","edname": "Lethbridge-East","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"69": {"map_id": "69","edname": "Lethbridge-West","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"70": {"map_id": "70","edname": "Little Bow","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"71": {"map_id": "71","edname": "Livingstone-Macleod","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"72": {"map_id": "72","edname": "Medicine Hat","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"73": {"map_id": "73","edname": "Olds-Didsbury-Three Hills","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"74": {"map_id": "74","edname": "Peace River","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"75": {"map_id": "75","edname": "Red Deer-North","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"76": {"map_id": "76","edname": "Red Deer-South","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"77": {"map_id": "77","edname": "Rimbey-Rocky Mountain House-Sundre","region": "Rest of Alberta","election_2012": "WRP","current_party": "Ind","totalvotes": "15000"},
"78": {"map_id": "78","edname": "Sherwood Park","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"79": {"map_id": "79","edname": "Spruce Grove-St. Albert","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"80": {"map_id": "80","edname": "St. Albert","region": "Edmonton","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"81": {"map_id": "81","edname": "Stony Plain","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"82": {"map_id": "82","edname": "Strathcona-Sherwood Park","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"83": {"map_id": "83","edname": "Strathmore-Brooks","region": "Rest of Alberta","election_2012": "WRP","current_party": "PC","totalvotes": "15000"},
"84": {"map_id": "84","edname": "Vermilion-Lloydminster","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"85": {"map_id": "85","edname": "West Yellowhead","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"86": {"map_id": "86","edname": "Wetaskiwin-Camrose","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},
"87": {"map_id": "87","edname": "Whitecourt-Ste. Anne","region": "Rest of Alberta","election_2012": "PC","current_party": "PC","totalvotes": "15000"},


  },
  
  "max_turnout": "39816"
}
